/**
 * Intelligence domain types.
 *
 * These types describe AI-derived (semantic) observations attached to Gleams.
 * They are intentionally kept separate from the core Gleam model
 * (see `gleam.ts`) — Repository data is immutable user knowledge;
 * Intelligence data is replaceable semantic interpretation.
 *
 * MANIFEST ch.3 (微光成形) and ch.11 (AI 之界) define this boundary.
 * Deleting every record described here must leave the Repository fully
 * functional.
 */

// ── Observation Status ─────────────────────────────────

/**
 * Processing state for a single semantic artifact.
 *
 * Each artifact (summary, tags, embedding, relation) maintains its own
 * state independently — failure of one capability never blocks the others.
 *
 *   Pending   → not yet started
 *   Running   → Scheduler has claimed the work
 *   Completed → artifact successfully generated
 *   Failed    → computation did not complete; may be retried
 *
 * Version 1 intentionally omits a Stale state. When a Prompt version
 * changes, existing Completed artifacts remain Completed; users request
 * regeneration explicitly through the GraphQL API.
 */
export type ObservationStatus = 'pending' | 'running' | 'completed' | 'failed'

// ── Artifact Types ─────────────────────────────────────

/**
 * The four semantic artifacts produced by Version 1.
 *
 * Each maps 1:1 to an Observation Stage and to a status/version field
 * inside `gleam_ai`.
 */
export type ArtifactType = 'summary' | 'tags' | 'embedding' | 'relation'

// ── gleam_ai ───────────────────────────────────────────

/**
 * Per-Gleam semantic observation record.
 *
 * One row per Gleam. Created by the Scheduler (not by Repository operations)
 * when it discovers a Gleam that has not yet been observed.
 *
 * The existence of a `gleam_ai` row indicates that semantic observation
 * has begun. Each `*_status` field tracks how far that specific artifact
 * has progressed.
 */
export interface GleamAI {
  gleamId: string
  provider: string | null
  model: string | null

  // Semantic artifacts (nullable until first successful generation)
  summary: string | null
  tags: string[] | null
  embedding: Buffer | null // Float32Array bytes (Float32Array.buffer)

  // Embedding-specific metadata (different models → different dimensions)
  embeddingModel: string | null
  embeddingDimensions: number | null

  // Per-artifact prompt version (provenance + reproducibility)
  summaryVersion: string | null
  tagVersion: string | null
  relationVersion: string | null

  // Per-artifact processing state
  summaryStatus: ObservationStatus
  tagStatus: ObservationStatus
  embeddingStatus: ObservationStatus
  relationStatus: ObservationStatus

  // Retry tracking (per-artifact)
  summaryRetryCount: number
  tagRetryCount: number
  embeddingRetryCount: number
  relationRetryCount: number

  // Last attempt timestamps (ISO 8601) for backoff scheduling
  summaryLastAttemptAt: string | null
  tagLastAttemptAt: string | null
  embeddingLastAttemptAt: string | null
  relationLastAttemptAt: string | null

  updatedAt: string
}

// ── gleam_relations ────────────────────────────────────

/**
 * Origin of a relation.
 *
 * `ai` relations are regenerated by the Relation Stage whenever it re-runs
 * for a Gleam — they are replaced wholesale.
 *
 * `user` relations are never automatically modified or deleted; they
 * survive AI regeneration.
 */
export type RelationOrigin = 'ai' | 'user'

/**
 * Type of semantic connection between two Gleams.
 *
 * Version 1 implements only `semantic_proximity`. Other types are reserved
 * for future versions (causal, evolutionary, synonymous, refutation,
 * finalization, errata, milestone summary, etc.).
 */
export type RelationType = 'semantic_proximity'

/**
 * A directed semantic connection between two Gleams.
 *
 * Stored in `gleam_relations`. For AI-generated relations, `strength`
 * holds the cosine similarity in embedding space. For user-created
 * relations, `strength` is null.
 *
 * UNIQUE(source_gleam_id, target_gleam_id, relation_type) prevents
 * duplicate edges of the same type.
 */
export interface GleamRelation {
  id: string // UUID v7
  sourceGleamId: string
  targetGleamId: string
  relationType: RelationType
  strength: number | null
  origin: RelationOrigin
  createdAt: string
}

// ── Intelligence Configuration ──────────────────────────

/**
 * Runtime provider configuration (decrypted form, never persisted).
 *
 * The `apiKey` is held in memory only by the Gateway at the point of
 * provider invocation. The Repository stores only the encrypted form.
 */
export interface IntelligenceConfig {
  provider: string
  model: string
  /** Embedding model. Always user-supplied — no server default. */
  embeddingModel: string
  endpoint: string
  encryptedApiKey: string // base64 ciphertext
  apiKeyIv: string // base64 IV
  updatedAt: string
}

/**
 * Provider configuration returned to GraphQL clients.
 *
 * The API key is never returned — only a boolean indicating presence.
 */
export interface IntelligenceConfigView {
  provider: string
  model: string
  /** Embedding model (always user-supplied). */
  embeddingModel: string
  endpoint: string
  hasApiKey: boolean
}

// ── Prompt History ─────────────────────────────────────

/**
 * Archived snapshot of a Prompt file.
 *
 * Whenever a Prompt version is used for the first time, its complete
 * content is archived. The `checksum` (sha256) serves three purposes:
 *   - deduplication (identical content stored once)
 *   - integrity verification
 *   - tamper detection
 *
 * Snapshots are never consulted during normal execution — their purpose
 * is historical explainability of previously generated artifacts.
 */
export interface PromptSnapshot {
  capability: string // 'summary' | 'tags' | 'relation' | ...
  version: string // 'v1', 'v2', ...
  content: string
  checksum: string
  createdAt: string
}

// ── Pending Artifact (Scheduler work item) ─────────────

/**
 * A unit of semantic work discovered by the Scheduler.
 *
 * The Scheduler queries for artifacts whose status is `pending` or
 * `failed` (with backoff elapsed). Each result bundles enough context
 * to drive one Observation Pipeline cycle for that Gleam.
 */
export interface PendingArtifact {
  gleamId: string
  artifact: ArtifactType
}

// ── Status helpers ─────────────────────────────────────

export const ARTIFACT_STATUSES: ArtifactType[] = ['summary', 'tags', 'embedding', 'relation']

/**
 * Maps an ArtifactType to its status field name on GleamAI.
 * Useful for generic status transitions in the Scheduler/Repository.
 */
export function statusFieldFor(artifact: ArtifactType): keyof GleamAI {
  switch (artifact) {
    case 'summary':
      return 'summaryStatus'
    case 'tags':
      return 'tagStatus'
    case 'embedding':
      return 'embeddingStatus'
    case 'relation':
      return 'relationStatus'
  }
}

/**
 * Maps an ArtifactType to its retry-count field name on GleamAI.
 */
export function retryCountFieldFor(artifact: ArtifactType): keyof GleamAI {
  switch (artifact) {
    case 'summary':
      return 'summaryRetryCount'
    case 'tags':
      return 'tagRetryCount'
    case 'embedding':
      return 'embeddingRetryCount'
    case 'relation':
      return 'relationRetryCount'
  }
}

/**
 * Maps an ArtifactType to its last-attempt field name on GleamAI.
 */
export function lastAttemptFieldFor(artifact: ArtifactType): keyof GleamAI {
  switch (artifact) {
    case 'summary':
      return 'summaryLastAttemptAt'
    case 'tags':
      return 'tagLastAttemptAt'
    case 'embedding':
      return 'embeddingLastAttemptAt'
    case 'relation':
      return 'relationLastAttemptAt'
  }
}
